spring.application.name=web-2026-II
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/institucionesdb
spring.datasource.username=usuario_software
spring.datasource.password=0000
server.port=8080
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
logging.level.org.hibernate=ERROR
